motech-development/platform

packages/breeze-ui/src/Alert/Alert.tsx, packages/breeze-ui/src/AppBar/AppBar.tsx, packages/breeze-ui/src/Avatar/Avatar.tsx, packages/breeze-ui/src/BaseButton/BaseButton.tsx, packages/breeze-ui/src/Button/Button.tsx, packages/breeze-ui/src/Calendar/Calendar.tsx, packages/breeze-ui/src/Card/Card.tsx, packages/breeze-ui/src/Col/Col.tsx, packages/breeze-ui/src/DatePicker/DatePicker.tsx, packages/breeze-ui/src/HelpText/HelpText.tsx, packages/breeze-ui/src/InputWrapper/InputWrapper.tsx, packages/breeze-ui/src/Label/Label.tsx, packages/breeze-ui/src/Legend/Legend.tsx, packages/breeze-ui/src/Loader/Loader.tsx, packages/breeze-ui/src/Masonry/Masonry.tsx, packages/breeze-ui/src/OptionLabel/OptionLabel.tsx, packages/breeze-ui/src/Row/Row.tsx, packages/breeze-ui/src/Select/Select.tsx, packages/breeze-ui/src/Table/Table.tsx, packages/breeze-ui/src/TableRow/TableRow.tsx, packages/breeze-ui/src/TextBox/TextBox.tsx, packages/breeze-ui/src/Tooltip/Tooltip.tsx, packages/breeze-ui/src/Typography/Typography.tsx
affects: @motech-development/breeze-ui
=> chore(ui): sort out props

.circleci/config.yml, packages/breeze-ui/src/BaseButton/BaseButton.tsx, packages/breeze-ui/src/Calendar/Calendar.tsx, packages/breeze-ui/src/Calendar/__tests__/Calendar.tsx
Fixes issue where datepicker would disappear when changing months/year
=> Date change bug fix

applications/accounts/api/src/shared/__tests__/transform-balance.ts, applications/accounts/api/src/shared/transform-balance.ts
=> fix(accounts): fix random balance entry

applications/accounts/client/public/locales/en/accounts.json, applications/accounts/client/src/pages/MyCompanies/Accounts/PendingTransactions.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/RecordTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/ViewTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/RecordTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/ViewTransaction.tsx
=> chore(accounts): pending transaction improvements

applications/accounts/client/config-overrides.js, applications/accounts/client/serverless.yml, applications/accounts/client/src/index.tsx, package-lock.json, package.json
Customise service worker to allow more control
=> Custom service worker

applications/core/comms/serverless.yml, applications/core/comms/src/__tests__/verify-domain.ts, applications/core/comms/src/verify-domain.ts
=> chore(core): add SPF record

applications/core/comms/serverless.yml, applications/core/infrastructure/serverless.yml
affects: @core/comms, @core/infrastructure
=> chore(core): update infrastructure for O365

applications/cypress/api/src/handlers/__tests__/github-status.test.ts, applications/cypress/api/src/handlers/github-status.ts
=> feat(cypress): cater for pr merge status updates

.github/workflows/teardown-environment.yml, README.md, applications/accounts/client/src/pages/MyCompanies/Reports/Reports.tsx, applications/accounts/client/src/pages/MyCompanies/Reports/__tests__/Reports.tsx, package.json, packages/s3-file-operations/__mocks__/aws-sdk.ts, packages/s3-file-operations/src/__tests__/s3-file-operations.ts, packages/s3-file-operations/src/s3-file-operations.ts, yarn.lock
=> feat: improve clean up

applications/accounts/client/package.json, applications/accounts/client/src/graphql/transaction/__tests__/DELETE_TRANSACTION.ts, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/Accounts.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/PendingTransactions.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/RecordTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/ViewTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/shared/__tests__/UploadAttachment.tsx, applications/accounts/client/src/pages/MyCompanies/Clients/__tests__/AddClient.tsx, applications/accounts/client/src/pages/MyCompanies/Clients/__tests__/UpdateDetails.tsx, applications/accounts/client/src/pages/MyCompanies/Reports/__tests__/CreateReport.tsx, applications/accounts/client/src/pages/MyCompanies/Reports/__tests__/Reports.tsx, applications/accounts/client/src/pages/MyCompanies/Settings/Bank/__tests__/Bank.tsx, applications/accounts/client/src/pages/MyCompanies/Settings/Bank/__tests__/Callback.tsx, applications/accounts/client/src/pages/MyCompanies/Settings/Bank/__tests__/SelectAccount.tsx, applications/accounts/client/src/pages/MyCompanies/Settings/__tests__/Settings.tsx, applications/accounts/client/src/pages/MyCompanies/__tests__/AddCompany.tsx, applications/accounts/client/src/pages/MyCompanies/__tests__/UpdateDetails.tsx, applications/accounts/client/src/pages/MyCompanies/__tests__/UserNotifications.tsx, packages/appsync-apollo/package.json, yarn.lock
affects: @accounts/client, @motech-development/appsync-apollo
closes: #190
=> chore(deps): bump @apollo/client from 3.3.13 to 3.4.4

.github/workflows/deploy-to-production.yml, .github/workflows/production-scheduled-tests.yml, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/Accounts.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/PendingTransactions.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/RecordTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/ViewTransaction.tsx, applications/accounts/client/src/pages/MyCompanies/Clients/__tests__/AddClient.tsx, applications/accounts/client/src/pages/MyCompanies/Clients/__tests__/UpdateDetails.tsx, applications/accounts/client/src/pages/MyCompanies/Reports/__tests__/CreateReport.tsx, applications/accounts/client/src/pages/MyCompanies/Reports/__tests__/Reports.tsx, applications/accounts/client/src/pages/MyCompanies/__tests__/AddCompany.tsx, applications/accounts/client/src/pages/MyCompanies/__tests__/UpdateDetails.tsx, package.json, scripts/sorry-cypress.sh, yarn.lock
=> test(accounts): try to fix race conditions

applications/accounts/api/src/handlers/get-balance.ts, applications/accounts/client/src/graphql/transaction/ADD_TRANSACTION.ts, applications/accounts/client/src/graphql/transaction/UPDATE_TRANSACTION.ts, applications/accounts/client/src/graphql/transaction/utils.ts, applications/accounts/client/src/pages/MyCompanies/Accounts/ViewTransaction.tsx, applications/accounts/client/src/setupTests.ts, applications/accounts/data/src/handlers/insert-scheduled-transactions.ts, applications/accounts/data/src/handlers/insert-transactions.ts, applications/accounts/data/src/handlers/insert-typeahead.ts, applications/accounts/data/src/handlers/remove-scheduled-transactions.ts, applications/accounts/data/src/handlers/remove-transactions.ts, applications/accounts/data/src/handlers/update-scheduled-transactions.ts, applications/accounts/data/src/handlers/update-transactions.ts, applications/core/anti-virus/__mocks__/@motech-development/logger.ts, applications/core/anti-virus/__mocks__/child_process.ts, applications/core/anti-virus/package.json, applications/core/anti-virus/src/handlers/update-definitions.ts, applications/core/anti-virus/src/shared/__tests__/clam-av.ts, applications/core/anti-virus/src/shared/clam-av.ts, packages/axios-hooks/src/axios-hooks.ts, packages/axios-hooks/src/types.ts, packages/breeze-ui/src/Modal/Modal.tsx, packages/breeze-ui/src/Typeahead/Typeahead.tsx
* The remaining critical is `TransactionForm.tsx`, which probably needs a full rewrite as it's a mess.
* The remaining major code smells are due to nested template literals, which is how `styled-components` work. Will be cleared up when we move away and use tailwind for styling
=> refactor: fix code smells

applications/accounts/client/cypress/integration/non-vat-registered.spec.ts, applications/accounts/client/cypress/integration/vat-registered.spec.ts, applications/accounts/client/src/components/TransactionsList.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/PendingTransactions.tsx, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/ViewTransaction.tsx, applications/accounts/reports/src/handlers/__tests__/transform-transactions.test.ts, applications/accounts/reports/src/handlers/transform-transactions.ts
=> fix(accounts): add id to exported file names

.github/workflows/deploy-to-environment.yml, applications/accounts/client/src/pages/MyCompanies/Accounts/__tests__/ViewTransaction.tsx
=> chore(ci): more pipeline changes [ci skip]

.github/workflows/deploy-to-develop.yml, .github/workflows/deploy-to-environment.yml, .github/workflows/deploy-to-production.yml, .github/workflows/production-scheduled-tests.yml, .github/workflows/teardown-environment.yml, applications/accounts/client/package.json, applications/id/client/package.json, package.json, packages/appsync-apollo/package.json, packages/breeze-ui/package.json, renovate.json, yarn.lock
=> chore: group updates

.github/workflows/deploy-to-develop.yml, .github/workflows/deploy-to-environment.yml, .github/workflows/deploy-to-production.yml, .github/workflows/production-scheduled-tests.yml, .github/workflows/teardown-environment.yml, applications/core/anti-virus/scripts/build.sh, yarn.lock
=> chore(ci): use node-version-file

.vscode/settings.json, applications/accounts/api/serverless.yml, applications/accounts/client/cypress/integration/non-vat-registered.spec.ts, applications/accounts/client/cypress/integration/vat-registered.spec.ts
affects: @accounts/api, @accounts/client
closes: #435
=> fix: balance timeout

applications/id/tenant/tenant.yaml
=> fix(id): update config

.github/workflows/deploy-to-environment.yml
=> ci: check for virus definitions

applications/accounts/api/package.json, applications/accounts/api/serverless.yml, applications/accounts/api/src/handlers/publish-notifications.ts, yarn.lock
Remove `cross-fetch` and make use of native Node 18 `fetch`.
=> feat: remove cross-fetch

.devcontainer/devcontainer.json, .yarn/plugins/@motech-development/plugin-dedupe.cjs, .yarn/plugins/@motech-development/plugin-prepare.cjs, .yarnrc.yml, packages/yarn-plugin-dedupe/.eslintrc.json, packages/yarn-plugin-dedupe/.prettierrc.json, packages/yarn-plugin-dedupe/.releaserc.json, packages/yarn-plugin-dedupe/index.js, packages/yarn-plugin-dedupe/package.json, packages/yarn-plugin-prepare/.eslintrc.json, packages/yarn-plugin-prepare/.prettierrc.json, packages/yarn-plugin-prepare/.releaserc.json, packages/yarn-plugin-prepare/index.js, packages/yarn-plugin-prepare/package.json, yarn.lock
Yarn plugins that will run dedupe and prepare commands post install.
=> feat: yarn plugins
